export interface DisplayStat {
  stat?: string        // undefined → separator entry
  label?: string
  value?: number       // raw number after pc/mod transform
  fmt?: string         // Lua format spec: "d", ".1f", "d%%", ".2f%%", ".2fs", etc.
  color?: string       // hex color without # (e.g. "E05030")
  separator?: boolean
}

// A single line in a stat breakdown.
// Text line:  { label: "200 (base)" }
// Slot line:  { base, total, source, sourceName, ... }  — equipment/source contribution
export interface BreakdownLine {
  label?: string          // text line
  base?: string           // slot: raw base value
  inc?: string | null     // slot: "x 1.50" string or null
  more?: string | null    // slot: "x 1.20" string or null
  total?: string          // slot: final value after multipliers
  source?: string         // slot: slot name (e.g. "Helm")
  sourceName?: string     // slot: item/source display name
}

// A single cell in a table-layout CalcRow
export interface CalcCell {
  value: string
  breakdownKey?: string
}

// Cluster jewel subgraph node (dynamically generated by Lua PassiveSpec:BuildSubgraph)
export interface ClusterNode {
  id: number
  name: string
  type: string
  x: number
  y: number
  mods: string[]
  out: number[]
  icon?: string
}

// Pre-rendered Calcs tab row from Lua CalcSections
export interface CalcRow {
  label: string        // row label (English, from CalcSections.lua)
  value: string        // pre-formatted value string, e.g. "12,345" / "75.4%" / "1,234 – 5,678"
  breakdownKey?: string  // if present, used for hover popover
  hidden: boolean      // true when condition not met (structure kept, frontend filters)
  cells?: CalcCell[]   // table-layout: one cell per column (overrides value/breakdownKey)
}

export interface CalcSubsection {
  label: string        // subsection label
  rows: CalcRow[]
  layout?: "table"     // if "table", render as multi-column grid
  columns?: Array<{ label: string; color?: string }>  // table column headers (hex color without #)
}

export interface CalcSection {
  id: string           // section id, e.g. "HitDamage"
  label: string        // section label (English)
  color?: string       // title color hex (from CalcSections colorCode, e.g. "E05030")
  defaultCollapsed: boolean
  column: "left-a" | "left-b" | "right"  // three-column assignment
  subsections: CalcSubsection[]
}

export interface CalcResult {
  stats: Record<string, number>
  warnings: string[]
  displayStats: DisplayStat[]
  // stat key -> array of breakdown text lines; only present when there is meaningful breakdown data
  breakdown?: Record<string, BreakdownLine[]>
  // Skill parts (calculation variants) for the current main active skill
  skillParts?: string[]
  skillPartIndex?: number
  skillPartGemGroupIndex?: number
  skillPartGemIndex?: number
  // Cluster jewel subgraph nodes for passive tree rendering
  clusterNodes?: ClusterNode[]
  // Pre-rendered Calcs tab section tree from Lua (matches CalcSections.lua structure)
  calcSections?: CalcSection[]
}

export interface SocketGroup {
  enabled: boolean
  label: string
  slot: string
  mainActiveSkill: number
  gems: GemInstance[]
}

export interface GemInstance {
  skillId: string
  gemId: string
  nameSpec: string
  level: number
  quality: number
  qualityId: string
  enabled: boolean
}

export interface Item {
  id: number
  rawText: string
  name: string
  base: string
  rarity: string
}

export interface BuildConfig {
  level: number
  className: string
  ascendClassName: string
  mainSocketGroup: number
  skills: SocketGroup[]
  tree: {
    treeVersion: string
    classId: number
    ascendClassId: number
    allocNodes: number[]
    jewels?: Record<number, number>  // nodeId → itemId
  }
  items: {
    itemList: Item[]
    slots: Record<string, number>
  }
  config: Record<string, unknown>
}

export interface CalculateResponse {
  sessionId: string
  buildConfig: BuildConfig
  result: CalcResult
}
