export interface DisplayStat {
  stat: string
  label: string
  value: string
  warn: boolean
  category: string
}

// A single line in a stat breakdown.
// Text line:  { label: "200 (base)" }
// Slot line:  { base, total, source, sourceName, ... }  — equipment/source contribution
export interface BreakdownLine {
  label?: string          // text line
  base?: string           // slot: raw base value
  inc?: string | null     // slot: "x 1.50" string or null
  more?: string | null    // slot: "x 1.20" string or null
  total?: string          // slot: final value after multipliers
  source?: string         // slot: slot name (e.g. "Helm")
  sourceName?: string     // slot: item/source display name
}

// Cluster jewel subgraph node (dynamically generated by Lua PassiveSpec:BuildSubgraph)
export interface ClusterNode {
  id: number
  name: string
  type: string
  x: number
  y: number
  mods: string[]
  out: number[]
  icon?: string
}

export interface CalcResult {
  stats: Record<string, number>
  warnings: string[]
  displayStats: DisplayStat[]
  // stat key -> array of breakdown text lines; only present when there is meaningful breakdown data
  breakdown?: Record<string, BreakdownLine[]>
  // Skill parts (calculation variants) for the current main active skill
  skillParts?: string[]
  skillPartIndex?: number
  skillPartGemGroupIndex?: number
  skillPartGemIndex?: number
  // Cluster jewel subgraph nodes for passive tree rendering
  clusterNodes?: ClusterNode[]
}

export interface SocketGroup {
  enabled: boolean
  label: string
  slot: string
  mainActiveSkill: number
  gems: GemInstance[]
}

export interface GemInstance {
  skillId: string
  gemId: string
  nameSpec: string
  level: number
  quality: number
  qualityId: string
  enabled: boolean
}

export interface Item {
  id: number
  rawText: string
  name: string
  base: string
  rarity: string
}

export interface BuildConfig {
  level: number
  className: string
  ascendClassName: string
  mainSocketGroup: number
  skills: SocketGroup[]
  tree: {
    treeVersion: string
    classId: number
    ascendClassId: number
    allocNodes: number[]
    jewels?: Record<number, number>  // nodeId → itemId
  }
  items: {
    itemList: Item[]
    slots: Record<string, number>
  }
  config: Record<string, unknown>
}

export interface CalculateResponse {
  sessionId: string
  buildConfig: BuildConfig
  result: CalcResult
}
